language: python

install:
  - pip install tox bcrypt libnacl

matrix:
  allow_failures:
    - python: 3.6-dev
  fast_finish: true
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: 3.4
      before_install:
        - .travis/build-libsodium.sh
      env:
        - TOXENV=py34
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
      before_install:
        - .travis/build-libsodium.sh
      env:
        - TOXENV=py35
    - os: linux
      sudo: required
      dist: trusty
      python: 3.6-dev
      before_install:
        - .travis/build-libsodium.sh
      env:
        - TOXENV=py36
    - os: osx
      osx_image: xcode8.1
      language: generic
      env:
        - CPPFLAGS=-I/usr/local/opt/openssl/include
        - LDFLAGS=-L/usr/local/opt/openssl/lib -L/usr/local/opt/libffi/lib
        - PATH=$HOME/.pyenv/bin:/usr/local/opt/openssl/bin:$PATH
        - TOXENV=py34
      before_install:
        - brew update
        - brew install libffi libsodium
        - eval "$(pyenv init -)"
        - pyenv install 3.4.5
        - pyenv local 3.4.5
        - pyenv rehash
    - os: osx
      osx_image: xcode8.1
      language: generic
      env:
        - CPPFLAGS=-I/usr/local/opt/openssl/include
        - LDFLAGS=-L/usr/local/opt/openssl/lib -L/usr/local/opt/libffi/lib
        - PATH=$HOME/.pyenv/bin:/usr/local/opt/openssl/bin:$PATH
        - TOXENV=py35
      before_install:
        - brew update
        - brew install libffi libsodium
        - eval "$(pyenv init -)"
        - pyenv install 3.5.2
        - pyenv local 3.5.2
        - pyenv rehash

script: tox
